ui:
  - changed-files:
      - any-glob-to-any-file:
          - "src/components/**/*"
          - "src/stories/**/*"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"

api:
  - changed-files:
      - any-glob-to-any-file:
          - "openapi/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**/*"
          - "src/**/*.spec.ts"
          - "src/**/*.stories.tsx"
